schemes = {'bibebook': {'.indent': [{'property': 'text-indent',
                                     'value': '1em',
                                     'operator': 'set'},
                                    {'property': 'margin',
                                     'value': '0',
                                     'operator': 'set'}],
                        '.bib-img': [{'property': 'height',
                                      'value': '100%',
                                      'operator': 'set'},
                                     {'property': 'width',
                                      'value': '100%',
                                      'operator': 'set'}],
                        '.bib-body': {'property': 'font-family',
                                      'value': '"Fontbase"',
                                      'operator': 'remove'}}}
